[package]
name = "multigrid"
version = "0.1.0"
authors = ["Magnus Ulimoen <flymagnus@gmail.com>"]
edition = "2018"


[dependencies]
sbp = { path = "../sbp", features = ["rayon"] }
hdf5 = "0.6.0"
rayon = "1.3.0"
indicatif = "0.14.0"
structopt = "0.3.13"
ndarray = "0.13.0"
json = "0.12.4"
